# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53d17a910da3c776c7f03d0b576521a88793c236b77073c44221ecb8e00ebeb0422327b29351219401e6e733b71386fca5046e12d137272c2b5e68de9535fcc6

test:
  secret_key_base: eff51b570fe4b51376241bab7af8b9c3e6af2fe45855091dc695305a9256bc053f8aa39afe93bb77ce0fcb25ed14165cad12f6f2a45d97381bd7adf81603aaab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
